python_tests(
    name="tests",
    dependencies=["src:lib_test", ":unwrapper_res"],
    resolve="py-reqs-dev",
)

resources(
    name="unwrapper_res",
    sources=["res/nested.zip", "res/no_target.zip"],
)
