name: Run Pants Tests
on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate-and-generate:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: '3.12.3' # Use the python version required by your repo

      - name: Initialize Pants
        uses: pantsbuild/actions/init-pants@main
        with:
          base-branch: main

      - name: Generate lockfiles
        run: pants generate-lockfiles

      - name: Validate autoformat and types
        run: pants lint check src/ test/

      - name: Run Tests
        run: pants test --output=all --test-force --use-coverage --coverage-py-report=console test/::

      - name: Generate Wheels
        run: pants package src/

      - name: Upload Wheels
        uses: actions/upload-artifact@main
        with:
          name: wheels
          path: |
            dist/*.whl
            dist/*.tar.gz
          if-no-files-found: error
